[mysql]
dsn="root@tcp(localhost)/dkms"
[server]
port=8080

[tls]
enable = false
certFile = "cert.pem"
keyFile = "cert.key"

[log]
level = "debug"

[enc]
server = "http://www.myprivacy.top:5000"
token = "burenshizheshigesha"